# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ac67da5d75c916c1ab93f8a2842c27b"
name = "php-ui-cities"
handle = "php-ui-cities"
application_url = "https://shopify-php-app-yxe2.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "velo-pk-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-php-app-yxe2.onrender.com/auth/callback",
  "https://shopify-php-app-yxe2.onrender.com/auth/shopify/callback",
  "https://shopify-php-app-yxe2.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
